# Generated by Django 5.2 on 2025-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0002_passwordresetotp_invitationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must change password on next login'),
        ),
    ]
