# Generated by Django 5.2 on 2025-06-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0003_customuser_must_change_password'),
    ]

    operations = [
    ]
