# Generated by Django 5.2 on 2025-06-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0004_auto_20250622_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_id'], name='employee_pr_employe_1a95c2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['department'], name='employee_pr_departm_e2b925_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active'], name='employee_pr_is_acti_7789a7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tenant', 'employee_id'], name='employee_pr_tenant__82e883_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tenant', 'department'], name='employee_pr_tenant__a37318_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='employee_pr_tenant__beca1d_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['employee_id'], name='excel_data__employe_9fd389_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['year', 'month'], name='excel_data__year_eeb86c_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['department'], name='excel_data__departm_9f8307_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['tenant', 'employee_id'], name='excel_data__tenant__bfe70c_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['tenant', 'year', 'month'], name='excel_data__tenant__75033c_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['tenant', 'department'], name='excel_data__tenant__badda1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['employee_id', 'year', 'month'], name='excel_data__employe_af905f_idx'),
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employee_profile',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='location_branch',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_friday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_monday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_saturday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_sunday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_thursday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_tuesday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='off_wednesday',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='ot_charge_per_hour',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='shift_start_time',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='tds_percentage',
        ),
    ]
