# Generated by Django 5.2 on 2025-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0005_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_employe_1a95c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_departm_e2b925_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_is_acti_7789a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_tenant__82e883_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_tenant__a37318_idx',
        ),
        migrations.RemoveIndex(
            model_name='employeeprofile',
            name='employee_pr_tenant__beca1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__employe_9fd389_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__year_eeb86c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__departm_9f8307_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__tenant__bfe70c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__tenant__75033c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__tenant__badda1_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarydata',
            name='excel_data__employe_af905f_idx',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='location_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='off_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ot_charge_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='employeeprofile',
            unique_together={('tenant', 'employee_id')},
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table=None,
        ),
    ]
