# Generated by Django 5.2 on 2025-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0006_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='shift_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='shift_start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
