# Generated by Django 5.2 on 2025-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0008_payrollperiod_calculatedsalary_salaryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
