# Generated by Django 5.2 on 2025-06-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0009_alter_employeeprofile_tds_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedsalary',
            name='employee_ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Employee's OT rate per hour", max_digits=10),
        ),
        migrations.AddField(
            model_name='calculatedsalary',
            name='employee_tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Employee's TDS percentage", max_digits=5),
        ),
    ]
