# Generated by Django 5.2 on 2025-06-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0010_add_employee_specific_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='late_minutes',
            field=models.IntegerField(default=0, help_text='Minutes late for work'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='ot_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Overtime hours worked', max_digits=5),
        ),
    ]
