# Generated by Django 5.2 on 2025-06-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0011_add_ot_late_to_daily_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('present_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_minutes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='excel_data.tenant')),
            ],
            options={
                'verbose_name': 'Monthly attendance summary',
                'verbose_name_plural': 'Monthly attendance summaries',
                'ordering': ['-year', '-month', 'employee_id'],
                'unique_together': {('tenant', 'employee_id', 'year', 'month')},
            },
        ),
    ]
