# Generated by Django 5.2 on 2025-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0012_monthlyattendancesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('PAID_LEAVE', 'Paid Leave'), ('OFF', 'Off Day')], max_length=10),
        ),
    ]
