# Generated by Django 5.2 on 2025-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0013_alter_dailyattendance_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_calculate_payroll',
            field=models.BooleanField(default=False, help_text='Automatically calculate payroll on 1st of each month for previous month'),
        ),
    ]
