# Generated by Django 5.2 on 2025-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0014_tenant_auto_calculate_payroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advanceledger',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dailyattendance',
            options={'managed': True, 'ordering': ['-date', 'employee_name']},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'managed': True, 'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddIndex(
            model_name='advanceledger',
            index=models.Index(fields=['tenant', 'employee_id', 'status'], name='advance_payroll_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceledger',
            index=models.Index(fields=['tenant', 'for_month'], name='advance_month_idx'),
        ),
        migrations.AddIndex(
            model_name='advanceledger',
            index=models.Index(fields=['employee_id', 'status'], name='advance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['tenant', 'employee_id', 'date'], name='attendance_payroll_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['tenant', 'date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['employee_id', 'attendance_status'], name='attendance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tenant', 'is_active'], name='employee_active_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['tenant', 'employee_id'], name='employee_id_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['is_active', 'employee_id'], name='employee_lookup_idx'),
        ),
        migrations.AlterModelTable(
            name='advanceledger',
            table='excel_data_advanceledger',
        ),
        migrations.AlterModelTable(
            name='dailyattendance',
            table='excel_data_dailyattendance',
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table='excel_data_employeeprofile',
        ),
    ]
