# Generated by Django 5.2 on 2025-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0015_add_payroll_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceledger',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance to be repaid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='advanceledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original advance amount', max_digits=12),
        ),
    ]
