# Generated by Django 5.2 on 2025-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0016_advanceledger_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceledger',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('REPAID', 'Repaid')], default='PENDING', max_length=20),
        ),
    ]
