# Generated by Django 5.2 on 2025-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0017_add_partially_paid_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['tenant', 'employee_id', '-year', '-month'], name='salary_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['employee_id', '-year', '-month'], name='salary_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydata',
            index=models.Index(fields=['tenant', '-year', '-month'], name='salary_period_idx'),
        ),
    ]
