# Generated by Django 5.2.6 on 2025-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0020_optimize_payroll_period_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_session_key',
            field=models.CharField(blank=True, help_text='Current active session key', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_created_at',
            field=models.DateTimeField(blank=True, help_text='When the current session was created', null=True),
        ),
    ]
