# Generated by Django 5.2.6 on 2025-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0021_add_session_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Unique subdomain identifier (optional)', max_length=100, null=True, unique=True),
        ),
    ]
