# Generated by Django 5.2.6 on 2025-09-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0023_add_email_verification'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward migration: rename 'salery' to 'salary' only if needed
            "DO $$\nBEGIN\n    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='excel_data_salarydata' AND column_name='salery') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='excel_data_salarydata' AND column_name='salary') THEN\n        ALTER TABLE excel_data_salarydata RENAME COLUMN salery TO salary;\n    END IF;\nEND$$;",
            # Reverse migration: rename 'salary' back to 'salery' only if needed
            "DO $$\nBEGIN\n    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='excel_data_salarydata' AND column_name='salary') AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='excel_data_salarydata' AND column_name='salery') THEN\n        ALTER TABLE excel_data_salarydata RENAME COLUMN salary TO salery;\n    END IF;\nEND$$;",
        ),
    ]
