# Generated by Django 5.2.6 on 2025-09-22 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0024_fix_salary_column_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', '-last_activity'], name='excel_data__ip_addr_ab9c12_idx'), models.Index(fields=['user', '-last_activity'], name='excel_data__user_id_5300f1_idx')],
                'unique_together': {('ip_address', 'user')},
            },
        ),
    ]
