CREATE INDEX idx_daily_attendance_tenant_date ON excel_data_dailyattendance(tenant_id, date);
CREATE INDEX idx_daily_attendance_tenant_employee_date ON excel_data_dailyattendance(tenant_id, employee_id, date);
CREATE INDEX idx_daily_attendance_date_status ON excel_data_dailyattendance(date, attendance_status);
CREATE INDEX idx_daily_attendance_tenant_dept_date ON excel_data_dailyattendance(tenant_id, department, date);
CREATE INDEX idx_daily_attendance_employee_id ON excel_data_dailyattendance(employee_id);
CREATE INDEX idx_monthly_summary_tenant_year_month ON excel_data_monthlyattendancesummary(tenant_id, year, month);
CREATE INDEX idx_monthly_summary_employee_year_month ON excel_data_monthlyattendancesummary(employee_id, year, month);
CREATE INDEX idx_salary_data_tenant_year_month ON excel_data_salarydata(tenant_id, year, month);
CREATE INDEX idx_salary_data_employee_year_month ON excel_data_salarydata(employee_id, year, month);
CREATE INDEX idx_salary_data_tenant_employee ON excel_data_salarydata(tenant_id, employee_id);
CREATE INDEX idx_salary_data_year_month_name ON excel_data_salarydata(year DESC, month DESC, name);
CREATE INDEX idx_employee_profile_tenant_active ON excel_data_employeeprofile(tenant_id, is_active);
CREATE INDEX idx_employee_profile_tenant_employee_id ON excel_data_employeeprofile(tenant_id, employee_id);
CREATE INDEX idx_employee_profile_tenant_created ON excel_data_employeeprofile(tenant_id, created_at DESC);
CREATE INDEX idx_employee_profile_tenant_name ON excel_data_employeeprofile(tenant_id, first_name, last_name);
CREATE INDEX idx_employee_profile_tenant_email ON excel_data_employeeprofile(tenant_id, email);
CREATE INDEX idx_employee_profile_tenant_mobile ON excel_data_employeeprofile(tenant_id, mobile_number);
CREATE INDEX idx_employee_profile_joining_date ON excel_data_employeeprofile(date_of_joining);
CREATE INDEX idx_custom_user_tenant_active ON excel_data_customuser(tenant_id, is_active);
CREATE INDEX idx_custom_user_email_active ON excel_data_customuser(email, is_active);
CREATE INDEX idx_custom_user_tenant_role ON excel_data_customuser(tenant_id, role);
CREATE INDEX idx_attendance_tenant_employee_date ON excel_data_attendance(tenant_id, employee_id, date DESC);
CREATE INDEX idx_attendance_date_desc ON excel_data_attendance(date DESC);
CREATE INDEX idx_advance_ledger_tenant_employee ON excel_data_advanceledger(tenant_id, employee_id);
CREATE INDEX idx_advance_ledger_tenant_date ON excel_data_advanceledger(tenant_id, advance_date DESC);
CREATE INDEX idx_advance_ledger_status_month ON excel_data_advanceledger(status, for_month);
CREATE INDEX idx_payment_tenant_employee ON excel_data_payment(tenant_id, employee_id);
CREATE INDEX idx_payment_tenant_date ON excel_data_payment(tenant_id, payment_date DESC);
CREATE INDEX idx_invitation_token_tenant ON excel_data_invitationtoken(tenant_id, is_used, expires_at);
CREATE INDEX idx_invitation_email_used ON excel_data_invitationtoken(email, is_used);
CREATE INDEX idx_password_reset_email_used ON excel_data_passwordresetotp(email, is_used, expires_at);
